"use client";

import { Activity, CircleStop, Play, Radio, RotateCcw, WifiOff } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type Sample = Record<string, number | string | boolean | null>;
type Status = { online: boolean; collector_id: string | null; mode: string | null; packet_rate_hz: number; dropped_frames: number; out_of_order_frames: number; last_packet_at: string | null; session_uid: string | null; recording: boolean; current_sample: Sample | null };
const offline: Status = { online:false,collector_id:null,mode:null,packet_rate_hz:0,dropped_frames:0,out_of_order_frames:0,last_packet_at:null,session_uid:null,recording:false,current_sample:null };

export function LiveSession() {
  const { data: initial = offline } = useQuery({ queryKey:["collector-status"], queryFn: async()=>{ const response=await fetch(`${API}/v1/collector/status`); if(!response.ok) throw new Error(); return response.json() as Promise<Status>; }, retry:false });
  const [status,setStatus]=useState(initial); const [samples,setSamples]=useState<Sample[]>([]); const [replaying,setReplaying]=useState(false);
  useEffect(()=>setStatus(initial),[initial]);
  useEffect(()=>{ let socket:WebSocket|undefined; let timer:number; let stopped=false; const connect=()=>{ if(stopped)return; socket=new WebSocket(API.replace(/^http/,"ws")+"/v1/live"); socket.onmessage=(event)=>{ const message=JSON.parse(event.data); if(message.status)setStatus(message.status); if(message.samples)setSamples((current)=>[...current,...message.samples].slice(-180)); }; socket.onclose=()=>{if(!stopped)timer=window.setTimeout(connect,1500);}; }; connect(); return()=>{stopped=true;clearTimeout(timer);if(socket){socket.onclose=null;socket.close();}}; },[]);
  const current=status.current_sample; const speedTrace=useMemo(()=>samples.map((sample,index)=>`${(index/Math.max(1,samples.length-1))*100},${86-Number(sample.speed_kph??0)/4}`).join(" "),[samples]);
  const startReplay=async()=>{setReplaying(true);try{await fetch(`${API}/v1/demo/replay`,{method:"POST"});}finally{window.setTimeout(()=>setReplaying(false),3500);}};
  return <div className="live-layout"><div className="surface-card"><div className="section-heading"><div><p className="eyebrow">{status.mode??"Live F1 2021"}</p><h2>{status.online?"Telemetry stream active":"Waiting for collector"}</h2></div><span className={`status-chip ${status.online?"":"muted"}`}><span className={`status-dot ${status.online?"live":"idle"}`}/>{status.online?"Connected":"Disconnected"}</span></div>
    {!status.online&&!replaying?<div className="connection-hero"><div className="connection-ring"><WifiOff size={32}/></div><h2>No collector connected</h2><p>Start the native Windows collector or run the bundled replay. Demo replay will animate this exact live interface through the ingestion API.</p><button className="button" onClick={startReplay}><Play size={16}/> Replay demo telemetry</button></div>:<><div className="live-readout"><Readout label="Current lap" value={String(current?.lap_number??"—")}/><Readout label="Lap time" value={current?`${(Number(current.current_lap_time_ms)/1000).toFixed(3)}s`:"—"}/><Readout label="Speed" value={current?`${current.speed_kph} km/h`:"—"}/><Readout label="Gear" value={String(current?.gear??"—")}/><Readout label="Throttle" value={current?`${Math.round(Number(current.throttle_0_1)*100)}%`:"—"}/><Readout label="Brake" value={current?`${Math.round(Number(current.brake_0_1)*100)}%`:"—"}/><Readout label="Steering" value={current?Number(current.steer_minus1_1).toFixed(2):"—"}/><Readout label="RPM" value={String(current?.rpm??"—")}/></div><div className="animated-trace" style={{marginTop:16}}><svg viewBox="0 0 100 90" preserveAspectRatio="none"><polyline className="trace-line" points={speedTrace||"0,80 100,80"}/></svg></div></>}
  </div><aside className="coach-side"><div className="surface-card"><div className="section-heading"><div><p className="eyebrow">Connection</p><h2>Collector status</h2></div><Radio size={18} color="var(--blue)"/></div><div className="technical-list"><Technical label="Game / format" value="F1 2021 / 2021"/><Technical label="Last packet" value={status.last_packet_at?new Date(status.last_packet_at).toLocaleTimeString():"Never"}/><Technical label="Packet rate" value={`${status.packet_rate_hz} Hz`}/><Technical label="Dropped estimate" value={String(status.dropped_frames)}/><Technical label="Out of order" value={String(status.out_of_order_frames)}/><Technical label="Session UID" value={status.session_uid?.slice(-8)??"—"}/></div></div><div className="surface-card"><div className="section-heading"><div><p className="eyebrow">Recording</p><h2>Local capture</h2></div>{status.recording?<CircleStop size={18} color="var(--critical)"/>:<Activity size={18}/>}</div><p className="muted" style={{fontSize:12,lineHeight:1.6}}>Raw packets and normalized JSONL are flushed by the collector. Recording control follows the native collector process.</p><button className="button secondary" style={{width:"100%"}} onClick={startReplay} disabled={replaying}><RotateCcw size={16}/>{replaying?"Replay running…":"Run replay again"}</button></div></aside></div>;
}
function Readout({label,value}:{label:string;value:string}){return <div className="readout"><span>{label}</span><strong>{value}</strong></div>}
function Technical({label,value}:{label:string;value:string}){return <div className="technical-row"><span>{label}</span><strong>{value}</strong></div>}
