import { ArrowLeft, Columns3, Download, Sparkles } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { TelemetryChart } from "@/components/TelemetryChart";
import { TrackMap } from "@/components/TrackMap";
import { DemoBanner, EvidenceCard, MetricCard, SectionHeading } from "@/components/UI";
import { getSession, telemetryForLaps } from "@/lib/data";
import { formatLapTime } from "@lapsignal/telemetry-domain";

export default async function SessionDetailPage({params}:{params:Promise<{sessionId:string}>}){
 const {sessionId}=await params; const session=await getSession(sessionId); if(!session)notFound(); const pace=session.metrics.pace; const clean=session.laps.filter((lap)=>lap.valid); const selected=clean.slice(0,2).map((lap)=>lap.lap_number); const traces=telemetryForLaps(session,selected);
 return <><DemoBanner/><div className="session-detail-head"><div><Link className="tag" href="/app/sessions"><ArrowLeft size={12}/> Session library</Link><h2>{session.track_name}</h2><p>{session.game_label} · {session.car_class} · {session.session_type} · {session.input_device}</p></div><div className="detail-actions"><Link className="button secondary small" href={`/app/compare?session=${session.id}`}><Columns3 size={14}/> Compare laps</Link><Link className="button small" href="/app/coach"><Sparkles size={14}/> Coach report</Link><button className="icon-button" aria-label="Export summary"><Download size={15}/></button></div></div>
 <div className="dashboard-grid"><div className="span-3"><MetricCard label="Best clean lap" value={formatLapTime(pace.best_lap_ms)} detail={`lap ${clean.find((lap)=>lap.lap_time_ms===pace.best_lap_ms)?.lap_number??"—"}`}/></div><div className="span-3"><MetricCard label="Theoretical best" value={formatLapTime(pace.theoretical_best_ms)} detail={`${((pace.best_lap_ms-pace.theoretical_best_ms)/1000).toFixed(3)} s available`}/></div><div className="span-3"><MetricCard label="Median clean lap" value={formatLapTime(pace.median_lap_ms)} detail={`${pace.clean_laps} clean laps`}/></div><div className="span-3"><MetricCard label="Consistency" value={`${pace.consistency_score}`} detail="robust score / 100"/></div>
 <section className="span-8 surface-card"><SectionHeading eyebrow="Stint overview" title="Clean-lap shape"/><div className="trend-chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none" role="img" aria-label="Lap time trend across the stint">{[30,80,130,180].map((y)=><line className="trend-grid" x1="0" x2="700" y1={y} y2={y} key={y}/>)}<polyline className="trend-line" points={session.laps.map((lap,index)=>`${index*(700/(session.laps.length-1))},${170-(lap.lap_time_ms-pace.best_lap_ms)/18}`).join(" ")}/>{session.laps.map((lap,index)=><circle className="trend-point" cx={index*(700/(session.laps.length-1))} cy={170-(lap.lap_time_ms-pace.best_lap_ms)/18} r="4" key={lap.id}/>)}</svg></div><div className="technical-list"><div className="technical-row"><span>Pace degradation</span><strong>{pace.pace_degradation_ms_per_lap} ms/lap</strong></div><div className="technical-row"><span>Long-run stability</span><strong>{session.metrics.stint.long_run_stability_score}/100</strong></div><div className="technical-row"><span>Tyre-wear correlation</span><strong>{session.metrics.stint.tyre_wear_correlation??"Not available"}</strong></div></div></section>
 <section className="span-4 surface-card"><SectionHeading eyebrow="Distance analysis" title="Time-loss zones"/><TrackMap/></section>
 <section className="span-12"><SectionHeading eyebrow="Verified findings" title="Highest-value signals"/><div className="findings-grid">{session.findings.map((finding)=><EvidenceCard finding={finding} key={finding.id}/>)}</div></section>
 <section className="span-12"><SectionHeading eyebrow="Distance aligned" title={`Telemetry · laps ${selected.join(" and ")}`}/><TelemetryChart traces={traces}/></section>
 <section className="span-8 surface-card table-card"><SectionHeading eyebrow="Lap preparation" title="Lap classification"/><LapTable laps={session.laps}/></section>
 <section className="span-4 surface-card"><SectionHeading eyebrow="Provenance" title="Analysis chain"/><div className="technical-list">{Object.entries(session.provenance).map(([key,value])=><div className="technical-row" key={key}><span>{key.replaceAll("_"," ")}</span><strong>{String(value)}</strong></div>)}</div></section></div></>;
}
function LapTable({laps}:{laps:import("@/lib/types").Lap[]}){return <table className="lap-table"><thead><tr><th><span className="sr-only">Select</span></th><th>Lap</th><th>Status</th><th>Sector 1</th><th>Sector 2</th><th>Lap time</th></tr></thead><tbody>{laps.map((lap)=><tr key={lap.id}><td><input className="lap-checkbox" type="checkbox" aria-label={`Select lap ${lap.lap_number}`}/></td><td className="mono">{lap.lap_number}</td><td><span className={`lap-status ${lap.valid?"":"invalid"}`}>{lap.valid?lap.classification:"Invalid"}</span></td><td className="mono">{formatLapTime(lap.sector_times_ms[0])}</td><td className="mono">{formatLapTime(lap.sector_times_ms[1])}</td><td className="lap-time">{formatLapTime(lap.lap_time_ms)}</td></tr>)}</tbody></table>}
