// Generated by `pnpm generate:client`. Do not edit by hand.
export type ApiPath = "/health" | "/v1/collector/heartbeat" | "/v1/collector/status" | "/v1/demo/replay" | "/v1/demo/reset" | "/v1/export" | "/v1/ingest/batches" | "/v1/local-data" | "/v1/profile" | "/v1/progress" | "/v1/reports/{report_id}" | "/v1/sessions" | "/v1/sessions/{session_id}" | "/v1/sessions/{session_id}/analyze" | "/v1/sessions/{session_id}/coach" | "/v1/sessions/{session_id}/coach/questions" | "/v1/sessions/{session_id}/finalize" | "/v1/sessions/{session_id}/laps" | "/v1/sessions/{session_id}/telemetry" | "/v1/version";
export type ApiSchemaName = "CoachQuestion" | "CollectorHeartbeat" | "DriverProfilePayload" | "HTTPValidationError" | "IngestBatch" | "TelemetrySample" | "ValidationError";
export const apiOperations = [
  {
    "method": "GET",
    "path": "/health"
  },
  {
    "method": "POST",
    "path": "/v1/collector/heartbeat"
  },
  {
    "method": "GET",
    "path": "/v1/collector/status"
  },
  {
    "method": "POST",
    "path": "/v1/demo/replay"
  },
  {
    "method": "POST",
    "path": "/v1/demo/reset"
  },
  {
    "method": "GET",
    "path": "/v1/export"
  },
  {
    "method": "POST",
    "path": "/v1/ingest/batches"
  },
  {
    "method": "DELETE",
    "path": "/v1/local-data"
  },
  {
    "method": "GET",
    "path": "/v1/profile"
  },
  {
    "method": "PUT",
    "path": "/v1/profile"
  },
  {
    "method": "GET",
    "path": "/v1/progress"
  },
  {
    "method": "GET",
    "path": "/v1/reports/{report_id}"
  },
  {
    "method": "GET",
    "path": "/v1/sessions"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{session_id}"
  },
  {
    "method": "POST",
    "path": "/v1/sessions/{session_id}/analyze"
  },
  {
    "method": "POST",
    "path": "/v1/sessions/{session_id}/coach"
  },
  {
    "method": "POST",
    "path": "/v1/sessions/{session_id}/coach/questions"
  },
  {
    "method": "POST",
    "path": "/v1/sessions/{session_id}/finalize"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{session_id}/laps"
  },
  {
    "method": "GET",
    "path": "/v1/sessions/{session_id}/telemetry"
  },
  {
    "method": "GET",
    "path": "/v1/version"
  }
] as const;
export type ApiOperation = (typeof apiOperations)[number];
