"use client";

import { CalendarDays, CheckCircle2, Gamepad2, Radio, Search, SlidersHorizontal } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { formatLapTime } from "@lapsignal/telemetry-domain";
import type { SessionSummary } from "@/lib/types";

export function SessionLibrary({sessions,status="ok"}:{sessions:SessionSummary[];status?:"ok"|"unreachable"|"invalid_response"|"server_error"}){
 const [search,setSearch]=useState(""); const [device,setDevice]=useState("all"); const [game,setGame]=useState("all"); const [category,setCategory]=useState("all"); const [sort,setSort]=useState("date");
 const filtered=useMemo(()=>sessions.filter((session)=>(!search||`${session.title} ${session.track_name} ${session.car_class}`.toLowerCase().includes(search.toLowerCase()))&&(device==="all"||session.input_device===device)&&(game==="all"||session.game_id===game)&&(category==="all"||session.car_class===category)).sort((a,b)=>sort==="best"?(a.best_lap_ms??Number.POSITIVE_INFINITY)-(b.best_lap_ms??Number.POSITIVE_INFINITY):sort==="consistency"?b.consistency_score-a.consistency_score:b.started_at.localeCompare(a.started_at)),[sessions,search,device,game,category,sort]);
 if(status!=="ok") return <section className="surface-card empty-stage"><div className="state-card warning"><Search size={20}/><div><strong>Local API unavailable</strong><p>Saved sessions could not be loaded. Start the API and refresh; collector connectivity does not remove stored sessions.</p></div></div></section>;
 return <><div className="section-heading"><div><p className="eyebrow">Recorded work</p><h2>{filtered.length} sessions</h2></div><span className="tag"><SlidersHorizontal size={13}/> Saved locally</span></div>{sessions.length?<div className="filters"><div className="field search-field"><label htmlFor="session-search">Search</label><div style={{position:"relative"}}><Search size={15} style={{position:"absolute",left:12,top:14,color:"var(--dim)"}}/><input id="session-search" className="input" style={{paddingLeft:36}} placeholder="Track, car or session" value={search} onChange={(event)=>setSearch(event.target.value)}/></div></div><Filter label="Game" value={game} onChange={setGame} options={[["all","All games"],["f1_2021","F1 2021"]]}/><Filter label="Input" value={device} onChange={setDevice} options={[["all","All inputs"],["controller","Controller"],["wheel","Wheel"],["unknown","Unknown"]]}/><Filter label="Category" value={category} onChange={setCategory} options={[["all","All categories"],["Formula","Formula"]]}/><Filter label="Sort" value={sort} onChange={setSort} options={[["date","Newest"],["best","Best lap"],["consistency","Consistency"]]}/></div>:null}
 {sessions.length===0?<section className="surface-card empty-stage"><Radio size={30}/><h2>No recorded sessions yet</h2><p>Completed sessions will appear here after telemetry is captured and finalized.</p><div className="detail-actions"><Link className="button" href="/app/live">Open Live Session</Link><Link className="button secondary" href="/app/settings">View setup</Link></div></section>:filtered.length?<div className="session-cards">{filtered.map((session)=><Link href={`/app/sessions/${session.id}`} className="session-card" key={session.id}><div className="session-card-top"><span className="tag">Saved telemetry</span><span className="tag"><CheckCircle2 size={12}/> {session.analysis_status}</span></div><div><h2>{session.track_name}</h2><p>{session.game_label} · {session.car_class} · {session.session_type}</p></div><div className="session-meta"><span><CalendarDays size={12}/> {new Date(session.started_at).toLocaleDateString("en",{month:"short",day:"numeric"})}</span><span><Gamepad2 size={12}/> {session.input_device}</span></div><div className="session-stats"><div><span>Best</span><strong>{formatLapTime(session.best_lap_ms)}</strong></div><div><span>Clean</span><strong>{session.clean_lap_count}/{session.lap_count}</strong></div><div><span>Consistency</span><strong>{session.consistency_score}</strong></div></div></Link>)}</div>:<div className="state-card"><Search size={20}/><div><strong>No matching sessions</strong><p>Clear a filter or try a track, car class, or game name.</p></div></div>}
 <div className="pagination"><span>Page 1 of 1 · {filtered.length} results</span><div><button className="button ghost small" disabled>Previous</button> <button className="button ghost small" disabled>Next</button></div></div></>;
}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <div className="field"><label>{label}</label><select className="select" value={value} onChange={(event)=>onChange(event.target.value)}>{options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>}
