"use client";

import { Download, ExternalLink, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { SectionHeading, StateCard } from "@/components/UI";

const API=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8000";
const versions: Array<[string, string]> = [
 ["App","0.1.0-alpha.1"],["Collector","0.1.0-alpha.1"],["API","0.1.0-alpha.1"],["Telemetry schema","1"],["F1 2021 adapter","0.1.0"],["Analysis pipeline","0.1.0"],["Coach prompt","coach-v1"],["Build","1"],["Git","local"]
];
const settingsTabs = [["profile","Driver profile"],["ai","AI and consent"],["data","Data controls"],["collector","Collector"],["about","About"]] as const;
export function SettingsView(){const [tab,setTab]=useState("profile");const [profile,setProfile]=useState({input:"controller",units:"metric",aiConsent:false,cloudAi:false});const [message,setMessage]=useState<string|null>(null);useEffect(()=>{const saved=localStorage.getItem("lapsignal-settings");if(saved)setProfile(JSON.parse(saved));},[]);const save=(next:typeof profile)=>{setProfile(next);localStorage.setItem("lapsignal-settings",JSON.stringify(next));setMessage("Settings saved locally.");void fetch(`${API}/v1/profile`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({experience_level:"intermediate",input_device:next.input,primary_interest:"mixed",coaching_goal:"consistency",units:next.units,ai_consent:next.aiConsent,cloud_ai_enabled:next.cloudAi})}).catch(()=>undefined)};const exportData=async()=>{let payload;try{payload=await(await fetch(`${API}/v1/export`)).json()}catch{payload={export_version:1,note:"Local demo export",profile}}const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download="lapsignal-export.json";anchor.click();URL.revokeObjectURL(url)};const deleteData=async()=>{if(!window.confirm("Delete local user telemetry? Seeded demo data will remain."))return;try{const response=await fetch(`${API}/v1/local-data?confirm=${encodeURIComponent("DELETE LOCAL DATA")}`,{method:"DELETE"});setMessage(response.ok?"Local user telemetry deleted. Demo data was preserved.":"The local API is offline; no data was changed.")}catch{setMessage("The local API is offline; no data was changed.")}};return <><div className="session-detail-head"><div><p className="eyebrow">Local-first controls</p><h2>Settings and privacy</h2><p>Cloud AI is opt-in. Raw telemetry remains local by design.</p></div></div><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{settingsTabs.map(([key,label])=><button className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav><section className="surface-card settings-section">
 {tab==="profile"&&<><SectionHeading eyebrow="Defaults" title="Driver profile"/><div className="setting-row"><div><strong>Input device preference</strong><p>Used when a game adapter cannot identify the device.</p></div><select className="select" style={{width:170}} value={profile.input} onChange={(event)=>save({...profile,input:event.target.value})}><option value="controller">Controller</option><option value="wheel">Wheel</option><option value="unknown">Unknown</option></select></div><div className="setting-row"><div><strong>Units</strong><p>Telemetry contracts remain metric internally.</p></div><select className="select" style={{width:170}} value={profile.units} onChange={(event)=>save({...profile,units:event.target.value})}><option value="metric">Metric</option><option value="imperial">Imperial display</option></select></div><a className="button secondary" href="/app/onboarding">Review onboarding</a></>}
 {tab==="ai"&&<><SectionHeading eyebrow="Explicit consent" title="AI coach controls"/><div className="setting-row"><div><strong>AI consent</strong><p>Allow compact derived evidence to be used by the optional coach.</p></div><button className={`toggle ${profile.aiConsent?"on":""}`} aria-pressed={profile.aiConsent} aria-label="Toggle AI consent" onClick={()=>save({...profile,aiConsent:!profile.aiConsent,cloudAi:profile.aiConsent?false:profile.cloudAi})}/></div><div className="setting-row"><div><strong>Cloud AI</strong><p>Requires consent and a server-side OpenAI API key. Raw captures are never uploaded.</p></div><button className={`toggle ${profile.cloudAi?"on":""}`} disabled={!profile.aiConsent} aria-pressed={profile.cloudAi} aria-label="Toggle cloud AI" onClick={()=>save({...profile,cloudAi:!profile.cloudAi})}/></div><StateCard title="Rule-based fallback is always available">No key or consent is required for deterministic coaching. Every claim still links to stored evidence.</StateCard></>}
 {tab==="data"&&<><SectionHeading eyebrow="Ownership" title="Export or delete local data"/><div className="setting-row"><div><strong>Export summary</strong><p>Download profile, sessions, findings, and provenance. High-frequency telemetry is excluded.</p></div><button className="button secondary small" onClick={exportData}><Download size={14}/> Export</button></div><div className="setting-row"><div><strong>Delete local user telemetry</strong><p>Removes local captures and queued user data. Demo fixtures stay available.</p></div><button className="button ghost small" style={{color:"var(--critical)"}} onClick={deleteData}><Trash2 size={14}/> Delete</button></div><StateCard title="Privacy summary">LapSignal is local-first. No secret is placed in the browser, and raw high-frequency telemetry is not sent to the LLM.</StateCard></>}
 {tab==="collector"&&<><SectionHeading eyebrow="F1 2021 on PS4" title="Collector connection"/><div className="technical-list"><Row label="Run in" value="Windows PowerShell"/><Row label="Bind address" value="0.0.0.0"/><Row label="UDP port" value="20777"/><Row label="Packet format" value="2021"/><Row label="Recommended rate" value="20Hz"/><Row label="API URL" value="http://localhost:8000"/></div><StateCard title="Same local network required">Use ipconfig to find the laptop IPv4 address. Enter it under UDP IP Address in F1 2021, and allow inbound UDP 20777 through Windows Firewall if needed.</StateCard></>}
 {tab==="about"&&<><SectionHeading eyebrow="Provenance" title="LapSignal versions"/><div className="technical-list">{versions.map(([label,value])=><Row label={label} value={value} key={label}/>)}</div><div className="setting-row"><div><strong>Compatibility</strong><p>Collector/API, adapter/schema, and stored analysis versions are matched.</p></div><span className="tag" style={{color:"var(--positive)"}}><ShieldCheck size={13}/> Compatible</span></div><p className="muted" style={{fontSize:11,lineHeight:1.6}}>LapSignal is an independent telemetry analysis prototype and is not affiliated with or endorsed by any game publisher, racing series, governing body, console manufacturer, or vehicle manufacturer.</p><a className="button secondary" href="/" target="_blank">Product page <ExternalLink size={14}/></a></>}
 {message&&<div className="state-card"><ShieldCheck size={18}/><div><strong>Local settings</strong><p>{message}</p></div></div>}
 </section></div></>}
function Row({label,value}:{label:string;value:string}){return <div className="technical-row"><span>{label}</span><strong>{value}</strong></div>}
