"use client";

import { Gauge, Layers3, RotateCcw, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { TelemetryChart } from "@/components/TelemetryChart";
import { MetricCard, SectionHeading } from "@/components/UI";
import type { Session, TelemetryTrace } from "@/lib/types";
import { formatLapTime } from "@lapsignal/telemetry-domain";

export function CompareWorkspace({session,traces}:{session:Session;traces:TelemetryTrace[]}){const [selected,setSelected]=useState<number[]>(traces.slice(0,2).map((trace)=>trace.lap_number)); const active=useMemo(()=>traces.filter((trace)=>selected.includes(trace.lap_number)),[traces,selected]); const toggle=(lap:number)=>setSelected((current)=>current.includes(lap)?current.length>2?current.filter((item)=>item!==lap):current:current.length<4?[...current,lap]:current); const best=Math.min(...active.map((trace)=>trace.lap_time_ms)); const slowest=Math.max(...active.map((trace)=>trace.lap_time_ms)); return <><div className="session-detail-head"><div><p className="eyebrow">Measured telemetry comparison</p><h2>{session.track_name}</h2><p>Select two to four clean laps. Traces share a distance cursor, zoom window, and exact-value tooltip.</p></div><div className="detail-actions"><button className="button secondary small" onClick={()=>setSelected(traces.slice(0,2).map((trace)=>trace.lap_number))}><RotateCcw size={14}/> Reset</button><button className="button small" onClick={()=>{const fastest=[...traces].sort((a,b)=>a.lap_time_ms-b.lap_time_ms).slice(0,2).map((trace)=>trace.lap_number);setSelected(fastest)}}><Gauge size={14}/> Fastest pair</button></div></div><section className="surface-card" style={{marginBottom:16}}><SectionHeading eyebrow="Clean laps" title={`${selected.length} laps selected`}/><div className="channel-toggles">{traces.map((trace)=><button className={selected.includes(trace.lap_number)?"active":""} aria-pressed={selected.includes(trace.lap_number)} onClick={()=>toggle(trace.lap_number)} key={trace.lap_number}><span className="channel-shape"/>Lap {trace.lap_number} · {formatLapTime(trace.lap_time_ms)}</button>)}</div></section><div className="dashboard-grid" style={{marginBottom:16}}><div className="span-4"><MetricCard icon={Layers3} label="Compared spread" value={`${((slowest-best)/1000).toFixed(3)} s`} detail="finish-line delta"/></div><div className="span-4"><MetricCard icon={ShieldCheck} label="Reference lap" value={`Lap ${active.find((trace)=>trace.lap_time_ms===best)?.lap_number}`} detail={formatLapTime(best)}/></div><div className="span-4"><MetricCard icon={Gauge} label="Theoretical best" value={formatLapTime(session.metrics.pace.theoretical_best_ms)} detail="best stored sectors"/></div></div><TelemetryChart traces={active}/><section className="surface-card" style={{marginTop:16}}><SectionHeading eyebrow="Evidence contract" title="How this comparison is built"/><div className="technical-list"><div className="technical-row"><span>Largest finish-line delta</span><strong>{((slowest-best)/1000).toFixed(3)} s</strong></div><div className="technical-row"><span>Alignment basis</span><strong>Lap distance (m)</strong></div><div className="technical-row"><span>Source quality</span><strong style={{color:"var(--positive)"}}>Recorded · API downsampled</strong></div></div></section></>}
