import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const apiDir = resolve(root, "services", "api");
const result = spawnSync(
  "uv",
  ["run", "python", "-c", "import json; from lapsignal.main import app; print(json.dumps(app.openapi()))"],
  { cwd: apiDir, encoding: "utf8", windowsHide: true }
);

if (result.status !== 0) {
  throw new Error(`OpenAPI generation failed: ${result.stderr || result.stdout}`);
}

const document = JSON.parse(result.stdout);
const paths = Object.keys(document.paths).sort();
const operations = paths.flatMap((path) =>
  Object.keys(document.paths[path])
    .filter((method) => ["get", "post", "put", "delete", "patch"].includes(method))
    .map((method) => ({ method: method.toUpperCase(), path }))
);
const schemas = Object.keys(document.components?.schemas ?? {}).sort();
const lines = [
  "// Generated by `pnpm generate:client`. Do not edit by hand.",
  `export type ApiPath = ${paths.map((path) => JSON.stringify(path)).join(" | ")};`,
  `export type ApiSchemaName = ${schemas.length ? schemas.map((name) => JSON.stringify(name)).join(" | ") : "never"};`,
  "export const apiOperations = " + JSON.stringify(operations, null, 2) + " as const;",
  "export type ApiOperation = (typeof apiOperations)[number];",
  "",
];
writeFileSync(resolve(root, "apps", "web", "lib", "generated-api.ts"), lines.join("\n"), "utf8");
console.log(`Generated ${operations.length} operations and ${schemas.length} schema names.`);
